#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-lda
Version  : 1.5.2
Release  : 49
URL      : https://cran.r-project.org/src/contrib/lda_1.5.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/lda_1.5.2.tar.gz
Summary  : Collapsed Gibbs Sampling Methods for Topic Models
Group    : Development/Tools
License  : LGPL-2.1 LGPL-2.1+
Requires: R-lda-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
and related models.  This includes (but is not limited
	     to) sLDA, corrLDA, and the mixed-membership stochastic
	     blockmodel.  Inference for all of these models is
	     implemented via a fast collapsed Gibbs sampler written
	     in C.  Utility functions for reading/writing data
	     typically used in topic models, as well as tools for
	     examining posterior distributions are also included.

%package lib
Summary: lib components for the R-lda package.
Group: Libraries

%description lib
lib components for the R-lda package.


%prep
%setup -q -n lda
pushd ..
cp -a lda buildavx2
popd
pushd ..
cp -a lda buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1714327859

%install
export SOURCE_DATE_EPOCH=1714327859
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/lda/DESCRIPTION
/usr/lib64/R/library/lda/INDEX
/usr/lib64/R/library/lda/Meta/Rd.rds
/usr/lib64/R/library/lda/Meta/data.rds
/usr/lib64/R/library/lda/Meta/demo.rds
/usr/lib64/R/library/lda/Meta/features.rds
/usr/lib64/R/library/lda/Meta/hsearch.rds
/usr/lib64/R/library/lda/Meta/links.rds
/usr/lib64/R/library/lda/Meta/nsInfo.rds
/usr/lib64/R/library/lda/Meta/package.rds
/usr/lib64/R/library/lda/NAMESPACE
/usr/lib64/R/library/lda/R/lda
/usr/lib64/R/library/lda/R/lda.rdb
/usr/lib64/R/library/lda/R/lda.rdx
/usr/lib64/R/library/lda/data/cora.cites.rda
/usr/lib64/R/library/lda/data/cora.documents.rda
/usr/lib64/R/library/lda/data/cora.titles.rda
/usr/lib64/R/library/lda/data/cora.vocab.rda
/usr/lib64/R/library/lda/data/datalist
/usr/lib64/R/library/lda/data/newsgroup.label.map.rda
/usr/lib64/R/library/lda/data/newsgroup.test.documents.rda
/usr/lib64/R/library/lda/data/newsgroup.test.labels.rda
/usr/lib64/R/library/lda/data/newsgroup.train.documents.rda
/usr/lib64/R/library/lda/data/newsgroup.train.labels.rda
/usr/lib64/R/library/lda/data/newsgroup.vocab.rda
/usr/lib64/R/library/lda/data/poliblog.documents.rda
/usr/lib64/R/library/lda/data/poliblog.ratings.rda
/usr/lib64/R/library/lda/data/poliblog.vocab.rda
/usr/lib64/R/library/lda/data/sampson.rda
/usr/lib64/R/library/lda/demo/lda.R
/usr/lib64/R/library/lda/demo/mmsb.R
/usr/lib64/R/library/lda/demo/nubbi.R
/usr/lib64/R/library/lda/demo/rtm.R
/usr/lib64/R/library/lda/demo/slda.R
/usr/lib64/R/library/lda/demo/sldamc.R
/usr/lib64/R/library/lda/help/AnIndex
/usr/lib64/R/library/lda/help/aliases.rds
/usr/lib64/R/library/lda/help/lda.rdb
/usr/lib64/R/library/lda/help/lda.rdx
/usr/lib64/R/library/lda/help/paths.rds
/usr/lib64/R/library/lda/html/00Index.html
/usr/lib64/R/library/lda/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/lda/libs/lda.so
/V4/usr/lib64/R/library/lda/libs/lda.so
/usr/lib64/R/library/lda/libs/lda.so
